### PR TITLE
format create_playlist.py + response Exception

### PR DESCRIPTION
**Pull request by Raymonzut**
- For readability, long lines have been line wrapped
- Added missing whitespace

### CODE REVIEW

**Comment by Raymonzut** [comment]
- Add and Implement ResponseException

**Comment by Raymonzut** [comment]
Because I was not careful regarding the branch for the pull request, both features are in the same pull request. Not that it is a problem; it is just annoying.

**Comment by Raymonzut** [comment]
Next features on my beta branch will be more error handling and unittests

**Comment by TheComeUpCode** [comment]
Thanks!

**Pull request merged**
